/**
 * The invite, as the single source.
 *
 * Two things read it: the local tool in `tools/invite`, which renders `docs/invite-email.html`
 * with `npm run preview`, and the parse-meal service, which builds the draft the admin page asks
 * for. One copy on purpose: two copies of an email drift, and the copy that drifts is the one you
 * send.
 *
 * It lives in `shared/` because both the service and the tool import it, and it stays free of
 * browser and Node APIs for the same reason `shared/meal-parse.ts` does.
 *
 * The HTML is table layout with every style inline because Gmail discards `<style>` blocks and
 * `@media` queries when markup is pasted into its composer. The palette is the app's own,
 * converted from the oklch tokens in `src/styles.css` to hex, because no mail client
 * understands oklch: cream `#f0ece4`, card `#fffdf9`, ink `#192217`, quiet ink `#5e6657`, leaf
 * green `#195c2e`, border `#e2ded2`. `--secondary` (pale green) and `--accent` (apricot) are
 * deliberately unused — the pale green belonged to a row of feature chips that read as a
 * product page rather than a note from a friend.
 */

export const SENDER_NAME = "Aman Kesarwani";

/**
 * Matches the email's opening, because a subject that describes the app would undo the first
 * sentence of the body. Easy to change in the draft before sending.
 */
export const SUBJECT = "Two things surprised me about how I eat";

export interface InviteRecipient {
  /** Their first name, for the greeting. */
  firstName: string;
  /** The address on `allowed_emails`. This is the one the invite is tied to. */
  invitedEmail: string;
}

/**
 * What `npm run preview` renders into the committed file, so it stays generic.
 *
 * These are the only two placeholders: whoever uses the preview by hand fills them in. The
 * tool substitutes real values and never writes this file.
 */
export const PREVIEW: InviteRecipient = {
  firstName: "{{First name}}",
  invitedEmail: "{{invited email}}",
};

/**
 * The message fields both transports hand to their composer.
 *
 * The content is assembled here so that the local tool and the service cannot disagree about
 * what an invite says: they differ only in how they post it, IMAP append versus the Gmail API.
 */
export function inviteMessageFields(
  recipient: InviteRecipient,
  senderAddress: string,
): {
  from: { name: string; address: string };
  to: { name: string; address: string };
  subject: string;
  text: string;
  html: string;
} {
  return {
    from: { name: SENDER_NAME, address: senderAddress },
    to: { name: recipient.firstName, address: recipient.invitedEmail },
    subject: SUBJECT,
    text: renderInviteText(recipient),
    html: renderInviteHtml(recipient),
  };
}

/** The HTML part. `multipart/alternative` carries this alongside the plain text below. */
export function renderInviteHtml({ firstName, invitedEmail }: InviteRecipient): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="color-scheme" content="light only" />
    <meta name="supported-color-schemes" content="light only" />
    <title>You're invited to NutriTrack</title>
    <!--
      Generated by tools/invite. Do not edit by hand: edit tools/invite/src/invite.ts and run
      "npm run preview" in that directory.
    -->
  </head>
  <body style="margin: 0; padding: 0; background-color: #f0ece4">
    <!-- Preheader: shown in the inbox next to the subject, hidden in the body. -->
    <div
      style="
        display: none;
        max-height: 0;
        max-width: 0;
        overflow: hidden;
        opacity: 0;
        font-size: 1px;
        line-height: 1px;
        color: #f0ece4;
      "
    >
      A week of tracking what I eat, and two things surprised me. Sign in with the address this
      landed in. The invite is tied to it.
      &nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
    </div>

    <table
      role="presentation"
      border="0"
      cellpadding="0"
      cellspacing="0"
      width="100%"
      style="background-color: #f0ece4"
    >
      <tr>
        <td align="center" style="padding: 32px 16px">
          <table
            role="presentation"
            border="0"
            cellpadding="0"
            cellspacing="0"
            style="
              width: 100%;
              max-width: 600px;
              background-color: #fffdf9;
              border: 1px solid #e2ded2;
              border-radius: 20px;
            "
          >
            <tr>
              <td style="padding: 40px 40px 8px 40px">
                <!-- Brand row -->
                <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                  <tr>
                    <td width="40" valign="middle">
                      <img
                        src="https://tracknutri.app/icons/icon-192.png"
                        width="40"
                        height="40"
                        alt="NutriTrack"
                        style="display: block; width: 40px; height: 40px; border-radius: 10px"
                      />
                    </td>
                    <td valign="middle" style="padding-left: 12px">
                      <span
                        style="
                          font-family:
                            &quot;Fraunces&quot;, Georgia, &quot;Times New Roman&quot;, serif;
                          font-size: 19px;
                          font-weight: 700;
                          letter-spacing: -0.01em;
                          color: #192217;
                        "
                        >NutriTrack</span
                      >
                    </td>
                  </tr>
                </table>

                <!-- Headline: the finding, not the tagline. -->
                <p
                  style="
                    margin: 28px 0 0 0;
                    font-family: &quot;Fraunces&quot;, Georgia, &quot;Times New Roman&quot;, serif;
                    font-size: 34px;
                    line-height: 1.05;
                    font-weight: 700;
                    letter-spacing: -0.02em;
                    color: #192217;
                  "
                >
                  Two things <em style="color: #195c2e">surprised</em> me.
                </p>
              </td>
            </tr>

            <tr>
              <td
                style="
                  padding: 24px 40px 0 40px;
                  font-family:
                    &quot;Manrope&quot;,
                    -apple-system,
                    BlinkMacSystemFont,
                    &quot;Segoe UI&quot;,
                    Roboto,
                    Helvetica,
                    Arial,
                    sans-serif;
                  font-size: 16px;
                  line-height: 1.6;
                  color: #192217;
                "
              >
                <p style="margin: 0 0 16px 0">Hi ${firstName},</p>

                <p style="margin: 0 0 16px 0">
                  I've been tracking what I eat for a week, and two things surprised me.
                </p>

                <p style="margin: 0 0 16px 0">
                  I eat far less protein than I assumed. And it isn't the meals that do the damage:
                  it's the snacks once I'm back from work, the handful of chips while dinner is
                  cooking. Those are what push a day past where I thought it landed.
                </p>

                <p style="margin: 0">
                  So I built this to track it. You photograph your plate, it reads what's on it, you
                  fix what it got wrong, and it tells you one thing: whether you're on pace. Saying
                  or typing a meal works too, if a photo is awkward.
                </p>
              </td>
            </tr>

            <!-- The bit people get wrong: which address is invited. -->
            <tr>
              <td style="padding: 24px 40px 0 40px">
                <table
                  role="presentation"
                  border="0"
                  cellpadding="0"
                  cellspacing="0"
                  width="100%"
                  style="background-color: #f4f0e6; border: 1px solid #e2ded2; border-radius: 14px"
                >
                  <tr>
                    <td
                      style="
                        padding: 16px 18px;
                        font-family:
                          &quot;Manrope&quot;,
                          -apple-system,
                          BlinkMacSystemFont,
                          &quot;Segoe UI&quot;,
                          Roboto,
                          Helvetica,
                          Arial,
                          sans-serif;
                        font-size: 15px;
                        line-height: 1.55;
                        color: #5e6657;
                      "
                    >
                      Sign in with
                      <strong style="color: #192217">${invitedEmail}</strong>. It's invite-only
                      and your invite is tied to that address, so use that one. If Google offers you
                      a list of accounts, pick it.
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <!-- Call to action -->
            <tr>
              <td align="center" style="padding: 28px 40px 0 40px">
                <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                  <tr>
                    <td
                      align="center"
                      bgcolor="#195c2e"
                      style="background-color: #195c2e; border-radius: 999px"
                    >
                      <a
                        href="https://tracknutri.app"
                        style="
                          display: inline-block;
                          padding: 16px 34px;
                          font-family:
                            &quot;Manrope&quot;,
                            -apple-system,
                            BlinkMacSystemFont,
                            &quot;Segoe UI&quot;,
                            Roboto,
                            Helvetica,
                            Arial,
                            sans-serif;
                          font-size: 16px;
                          font-weight: 700;
                          color: #fbf8f1;
                          text-decoration: none;
                          border-radius: 999px;
                        "
                        >Open NutriTrack</a
                      >
                    </td>
                  </tr>
                </table>
                <p
                  style="
                    margin: 12px 0 0 0;
                    font-family:
                      &quot;Manrope&quot;,
                      -apple-system,
                      BlinkMacSystemFont,
                      &quot;Segoe UI&quot;,
                      Roboto,
                      Helvetica,
                      Arial,
                      sans-serif;
                    font-size: 12px;
                    line-height: 1.5;
                    color: #5e6657;
                  "
                >
                  or paste this in: <span style="color: #195c2e">tracknutri.app</span>
                </p>
              </td>
            </tr>

            <tr>
              <td
                style="
                  padding: 26px 40px 0 40px;
                  font-family:
                    &quot;Manrope&quot;,
                    -apple-system,
                    BlinkMacSystemFont,
                    &quot;Segoe UI&quot;,
                    Roboto,
                    Helvetica,
                    Arial,
                    sans-serif;
                  font-size: 16px;
                  line-height: 1.6;
                  color: #192217;
                "
              >
                <p style="margin: 0 0 16px 0">
                  One honest thing: the numbers come from a photo, so they're estimates, and
                  portions of calorie-dense things are the roughest part. A bowl of hummus can be
                  out by more than you'd guess. Nothing saves until you've looked at it, which is
                  what that screen is for.
                </p>

                <p style="margin: 0">
                  On an iPhone, add it to your home screen and it behaves like an app. That part is
                  Safari only: open tracknutri.app in Safari, tap Share, then Add to Home Screen.
                  And if something breaks or reads wrong, reply to this. I want to know.
                </p>
              </td>
            </tr>

            <tr>
              <td
                style="
                  padding: 24px 40px 0 40px;
                  font-family:
                    &quot;Manrope&quot;,
                    -apple-system,
                    BlinkMacSystemFont,
                    &quot;Segoe UI&quot;,
                    Roboto,
                    Helvetica,
                    Arial,
                    sans-serif;
                  font-size: 16px;
                  line-height: 1.6;
                  color: #192217;
                "
              >
                <p style="margin: 0">${SENDER_NAME}</p>
              </td>
            </tr>

            <!-- Close -->
            <tr>
              <td style="padding: 28px 40px 40px 40px">
                <table
                  role="presentation"
                  border="0"
                  cellpadding="0"
                  cellspacing="0"
                  width="100%"
                  style="border-top: 1px solid #e2ded2"
                >
                  <tr>
                    <td
                      style="
                        padding-top: 18px;
                        font-family:
                          &quot;Manrope&quot;,
                          -apple-system,
                          BlinkMacSystemFont,
                          &quot;Segoe UI&quot;,
                          Roboto,
                          Helvetica,
                          Arial,
                          sans-serif;
                        font-size: 12px;
                        line-height: 1.6;
                        color: #5e6657;
                      "
                    >
                      <a
                        href="https://tracknutri.app"
                        style="color: #195c2e; text-decoration: underline"
                        >tracknutri.app</a
                      >
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
`;
}

/**
 * The plain-text part.
 *
 * Not derived from the HTML: stripping tags produces a worse read than writing it out, and the
 * instruction about which address to sign in with has to survive the fallback, because that is
 * the part people get wrong. Kept beside the HTML so both are edited together.
 */
export function renderInviteText({ firstName, invitedEmail }: InviteRecipient): string {
  return `Hi ${firstName},

I've been tracking what I eat for a week, and two things surprised me.

I eat far less protein than I assumed. And it isn't the meals that do the damage: it's the
snacks once I'm back from work, the handful of chips while dinner is cooking. Those are what
push a day past where I thought it landed.

So I built this to track it. You photograph your plate, it reads what's on it, you fix what it
got wrong, and it tells you one thing: whether you're on pace. Saying or typing a meal works
too, if a photo is awkward.

Sign in with ${invitedEmail}. It's invite-only and your invite is tied to that address, so use
that one. If Google offers you a list of accounts, pick it.

https://tracknutri.app

One honest thing: the numbers come from a photo, so they're estimates, and portions of
calorie-dense things are the roughest part. A bowl of hummus can be out by more than you'd
guess. Nothing saves until you've looked at it, which is what that screen is for.

On an iPhone, add it to your home screen and it behaves like an app. That part is Safari only:
open tracknutri.app in Safari, tap Share, then Add to Home Screen. And if something breaks or
reads wrong, reply to this. I want to know.

${SENDER_NAME}
`;
}
